version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
        depends_on:
            - db
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ramses
            MYSQL_USER: ramses
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - persistent-db:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ramses
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        networks:
            - default
volumes:
    persistent-db: